services:
  - type: web
    name: autobetbot
    env: node
    region: oregon
    plan: free
    rootDir: bdg
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/bdg/.cache/puppeteer
      - key: NODE_VERSION
        value: 24.14.1
