services:
  - type: web
    name: autobetbot
    env: node
    region: oregon
    plan: free
    buildCommand: cd bdg && npm install && PUPPETEER_CACHE_DIR=/opt/render/project/src/bdg/.cache node node_modules/@puppeteer/browsers/lib/main-cli.js install chrome
    startCommand: cd bdg && npm start
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/bdg/.cache
      - key: NODE_VERSION
        value: 24.14.1
      - key: SUPABASE_URL
        value: https://qyzyqqxixluveqgwvfgx.supabase.co
      - key: SUPABASE_ANON_KEY
        value: sb_publishable_AmzY5reQUtAX7TLX84OL7g_oc6lvQ3N
